### ISSUE TITLE
tail: invalid PID: ''

### ISSUE THREAD

**Issue by dkcas11** [ich777/docker-steamcmd-server#22]
Hey, i'm getting an error with a missing PID, al though for the first part of startup the PID is found. It looks like some PID is not passed along. Any idea how to fix this?
Running on macOS 12.3 Monterey, Docker 4.6.1, Compose 2.3.3.

Im using docker compose, my config looks like this:
```
---
version: "2"
services:
    vrising:
        image: ich777/steamcmd:vrising
        container_name: vrising
        environment:
          - GAME_ID=1829350
          - SERVER_NAME='V Rising Docker'
          - WORLD_NAME='world1'
          - UID=501
          - GID=20
        volumes:
          - ~/v-rising-server/steamcmd:/serverdata/steamcmd
          - ~/v-rising-server/vrising:/serverdata/serverfiles
        ports:
          - 9876-9877:9876-9877/udp
```

This is the output:
```
[+] Running 1/0
 ⠿ Container vrising  Created                                                                                                                                                   0.0s
Attaching to vrising
vrising  | ---Ensuring UID: 501 matches user---
vrising  | usermod: no changes
vrising  | ---Ensuring GID: 20 matches user---
vrising  | usermod: no changes
vrising  | ---Setting umask to 000---
vrising  | ---Checking for optional scripts---
vrising  | ---No optional script found, continuing---
vrising  | ---Taking ownership of data...---
vrising  | ---Starting...---
vrising  | ---Update SteamCMD---
vrising  | Redirecting stderr to '/serverdata/Steam/logs/stderr.txt'
vrising  | [  0%] Checking for available updates...
vrising  | [----] Verifying installation...
vrising  | Steam Console Client (c) Valve Corporation - version 1653101151
vrising  | -- type 'quit' to exit --
vrising  | Loading Steam API...OK
vrising  | 
vrising  | Connecting anonymously to Steam Public...OK
vrising  | Waiting for client config...OK
vrising  | Waiting for user info...OK
vrising  | ---Update Server---
vrising  | Redirecting stderr to '/serverdata/Steam/logs/stderr.txt'
vrising  | [  0%] Checking for available updates...
vrising  | [----] Verifying installation...
vrising  | Steam Console Client (c) Valve Corporation - version 1653101151
vrising  | -- type 'quit' to exit --
vrising  | Loading Steam API...OK
vrising  | "@sSteamCmdForcePlatformType" = "windows"
vrising  | 
vrising  | Connecting anonymously to Steam Public...OK
vrising  | Waiting for client config...OK
vrising  | Waiting for user info...OK
vrising  | Success! App '1829350' already up to date.
vrising  | ---Checking if WINE workdirectory is present---
vrising  | ---WINE workdirectory found---
vrising  | ---Checking if WINE is properly installed---
vrising  | ---WINE properly set up---
vrising  | ---Checking for old display lock files---
vrising  | ---Server ready---
vrising  | ---Start Server---
vrising  | tail: invalid PID: ‘’
```
after that the license is posted following a "Terminated" line.
