### ISSUE TITLE
vrising tail: invalid PID: '' when launching 

### ISSUE THREAD

**Issue by KingPin** [ich777/docker-steamcmd-server#36]
Docker Version:  24.0.2
Host OS : Ubuntu 22.04

```
  V-Rising:
    container_name: V-Rising
    image: ich777/steamcmd:vrising
    restart: unless-stopped
    environment:
      - GAME_ID=1829350
      - SERVER_NAME=zzzzz
      - WORLD_NAME=xxxx
      - UID=1001
      - GID=1001
      - ENABLE_BEPINEX=true
    volumes:
      - ./server:/serverdata/steamcmd
      - ./data:/serverdata/serverfiles
    ports:
      - '9876-9877:9876-9877/udp'
```

when launching I get the error : 
```
vrising  | ---Checking if WINE workdirectory is present---
vrising  | ---WINE workdirectory found---
vrising  | ---Checking if WINE is properly installed---
vrising  | ---WINE properly set up---
vrising  | ---Checking for old display lock files---
vrising  | ---Server ready---
vrising  | ---Start Server---
vrising  | tail: invalid PID: ‘’
```

this is a clean install. I saw it on #22  but no resolution there so I'm not sure what Info to provide to help resolve this.

Thank you.
