### ISSUE TITLE
Palworld - Prevented from transfering save to container due to steamclient.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Maltahl** [ich777/docker-steamcmd-server#52]
Hi i recently went from a barebone non persistent data setup with SteamCMD to your container and wanted to try out your container setup as it seems more mature and easy to have in upkeep.

Anywho i stomped upon a problem with: steamclient.so: cannot open shared object file: No such file or directory
this prevents Palworld from giving correct access to players when copying a save as mentioned by: 
https://tech.palworldgame.com/dedicated-server-guide#linux

i also found that the server keeps looking for srcds_run to run instead of PalServer.sh so i had cp PalServer.sh to srcds_run inside /mnt/user/appdata/palworld

but to fix steamclient.so problems
I had to resort to this:

boot container as docker compose

```
version: "3.0"
services:
  palworld:
    image: ich777/steamcmd:latest
    restart: unless-stopped
    container_name: palworld
    environment:
      - GAME_ID=2394010
      - GAME_NAME=PalServer
      - GAME_PORT=8211
      - GAME_PARAMS=-players=32 -useperfthreads -NoAsyncLoadingThread -UseMul-ServerName=Servernamehere -AdminPassword=passwordofyourchoice
      - UID=99
      - GID=100
    volumes:
      - /mnt/user/appdata/steamcmd:/serverdata/steamcmd
      - /mnt/user/appdata/palworld:/serverdata/serverfiles
  
    network_mode: "bridge"

    ports:
      - "8211:8211/tcp"
      - "8211:8211/udp"
```

Then wait for container to boot, download and setup game.

Now enter the container, swap to steam as user
run this to get ".steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory" away

```
mkdir -p ~/.steam/sdk64/
./steamcmd.sh +login anonymous +app_update 1007 +quit
cp ~/Steam/steamapps/common/Steamworks\ SDK\ Redist/linux64/steamclient.so ~/.steam/sdk64/
```

exit container and stop it, not destroy.

Then remove the folder "Pal" inside /mnt/user/appdata/palworld

copy over backup from PalServer

Profit.

It might be an idea to add 
./steamcmd.sh +login anonymous +app_update 1007 +quit

to the build to avoid issues with other game containers.
