### ISSUE TITLE
using this repo, outside UNRAID

### ISSUE THREAD

**Issue by luckyzor** [ich777/docker-steamcmd-server#64]
I'm a user of unraid on my homelab, but I have a dedicated server to host gameservers outside, with another OS.

what should I change, if there are anything really unraid config, to porper use your repo in another OS?

I really like your work it's amazing and I really wanted to use it, outside unraid.
I wanted to test v-rising to start :)

thanks

**Comment by ich777** [comment]
Not much, just make sure the path's are correct and that the `UID` and `GID` environment variable are set to a UID and GID that Docker is able to actually access (on Debian based distributions most of the times `1000` is fine).

Also make sure that your distribution and Docker is up to date.

**Comment by luckyzor** [comment]
hmm thanks for the help
I tried to start the server; but its in a loop:
```
---BepInEx v1.668.5 up-to-date---
---Checking if WINE workdirectory is present---
---WINE workdirectory found---
---Checking if WINE is properly installed---
---WINE properly set up---
---Checking for old display lock files---
---Server ready---
---Start Server---
tail: invalid PID: ‘’
Terminated
```
docker-compose:
```
services:
  steamcmd:
    container_name: vrserver1
    image: ich777/steamcmd:vrising
    restart: unless-stopped
    ports:
        - 9876-9877:9876-9877/udp
        - 27016:27015/tcp
        - 27016:27015/udp
    environment:
        - GAME_ID=1829350
        - SERVER_NAME=V Rising Server 1 - PvE
        - WORLD_NAME=world1pve
        - UID=1000
        - GID=1000
        - GAME_PORT=27015
        - ENABLE_BEPINEX=true
    volumes:
        - /vrserver1/steamcmd:/serverdata/steamcmd
        - /vrserver1/serverfiles:/serverdata/serverfiles
```

anything I need to change?
